const texts =
{
    EN:
    {
        HOME_PAGE_TITLE: 'Dubai Shopping Festival',
        HOME_PAGE_DAY: 'Days',
        HOME_PAGE_HOUR:	'Hours',
        HOME_PAGE_MINUTE: 'Minutes',
        HOME_PAGE_MESSAGE1: 'Quest (6th - 13th Jan) Ends In',

        HOME_PAGE_NEXT_REWARD: 'Next Reward',
        HOME_PAGE_REWARD_1: 'Grand prize of AED 25,000 worth of Club Apparel points',
        HOME_PAGE_REWARD_2: 'An AED 1,000 worth of Club Apparel points',
        HOME_PAGE_REWARD_3: 'An AED 100 worth of vouchers across 50+ brands',
        HOME_PAGE_COMPLETE_LEVEL: 'Complete challenge %%d to get a voucher',
        HOME_PAGE_UNLOCK_LEVEL: 'Unlock new challenge %%d to play',

        WELCOME_1: 'welcome to',
        WELCOME_2: 'yalla dsf',
        WELCOME_3: 'presented by',
        WELCOME_4: 'club apparel',
        WELCOME_5: 'Play game to get instant rewards and explore Dubai',
        WELCOME_6: 'Grand prize of',
        WELCOME_7: 'worth of Club Apparel points',
        WELCOME_8: 'worth of Club Apparel points',
        WELCOME_9: 'worth of vouchers across 20+ brands',
        WELCOME_LABEL: 'next',

        REWARD_1: 'new reward',
        REWARD_2: 'Congratulations!',
        REWARD_3: 'You have won a voucher worth AED 100 at %%s.',
        REWARD_4: 'Go to your game wallet to redeem now.',
        REWARD_5: 'continue',
        
        TUTORIAL_PLAY_GAME: 'play game',
        TUTORIAL_PLAY_GAME_1: 'Tap on the button to play the game and complete the challenge.',
        TUTORIAL_PLAY_GAME_2: 'next',
        TUTORIAL_REWARDS: 'earn rewards',
        TUTORIAL_REWARDS_1a: 'AED 100',
        TUTORIAL_REWARDS_1b: ' worth of vouchers across 50+ brands.',
        TUTORIAL_REWARDS_1c: '100 lucky winners everyday.',
        TUTORIAL_REWARDS_2a: 'AED 1,000',
        TUTORIAL_REWARDS_2b: ' worth of Club Apparel points.',
        TUTORIAL_REWARDS_2c: 'Top 50 winners every week.',
        TUTORIAL_REWARDS_3a: 'Grand prize of ',
        TUTORIAL_REWARDS_3b: 'AED 25,000',
        TUTORIAL_REWARDS_3c: ' worth of Club Apparel points.',
        TUTORIAL_REWARDS_3d: '2 lucky winners.',
        TUTORIAL_REWARDS_4: 'next',
        TUTORIAL_UNLOCK: 'Unlock new challenge',
        TUTORIAL_UNLOCK_1: 'Go to any of the DSF locations across the city to unlock a new challenge and win more prizes.',
        TUTORIAL_UNLOCK_2: 'next',
        TUTORIAL_MAP_HELP: 'Challenge Map help',
        TUTORIAL_MAP_HELP_1a: 'Tap the',
        TUTORIAL_MAP_HELP_1b: ' icon to view all details on how to play.',
        TUTORIAL_MAP_HELP_2: 'done',

        QUEST_PLAY_NOW: 'Play Now',
        QUEST_UNLOCK_CHALLENGE: 'Unlock Challenge',

        LOCATION_INFO_1: 'location info',
        LOCATION_INFO_2: 'Tap on GPS icon to get more information about the unlock challenges.',
        LOCATION_INFO_3: 'done',
        LOCATION_UNLOCK_SUCCESS_1: 'Congratulation!',
        LOCATION_UNLOCK_SUCCESS_2: 'New game level is unlocked.',
        LOCATION_UNLOCK_SUCCESS_3: 'continue',
        LOCATION_UNLOCK_FAIL_1: 'Oops!',
        LOCATION_UNLOCK_FAIL_2: 'Please check your location and try again.',
        LOCATION_UNLOCK_FAIL_3: 'try again',

        HELP_QUESTMAP_LABEL: 'Challenge Map',
        HELP_QUESTMAP_1: 'Tap on the button to play the game – It’s just 30 seconds!',
        HELP_QUESTMAP_2: 'Go to any of the DSF locations across the city to unlock new challenges  and win more prizes at every step. Look out for the map with 20 locations to choose from!',
        HELP_QUESTMAP_3: 'Complete a challenge for a chance to win AED 100 worth of vouchers across 50+ brands. 100 lucky winners every day.',
        HELP_QUESTMAP_4: 'Compete with other players and get in the top leaderboard for a chance to win AED 1,000 worth of Club Apparel points. Top 50 winners every week – Look out for the leaderboard!',
        HELP_QUESTMAP_5: 'Complete all 3 challenges for a chance to win the Grand prize- AED 25,000 worth of Club Apparel points. 2 lucky winners at the end of Yalla DSF event',
        HELP_QUESTMAP_6: 'Don’t miss your voucher in wallet to redeem all your prizes',
        HELP_LOCATIONS_LABEL: 'Locations',
        HELP_LOCATIONS_1: 'Tap on GPS icon to get more information about the unlock challenges.',
        HELP_LOCATIONS_2: 'Go to any of 20 places.',
        HELP_LOCATIONS_3: 'Turn on Wifi or mobile data',
        HELP_LOCATIONS_4: 'Click on the "Unlock challenge" button to unlock new game level',
        HELP_LOCATIONS_5: 'A pop-up will appear to notify the unlock status',
        HELP_WALLET_LABEL: 'Wallet',
        HELP_WALLET_1: 'You can check out all the rewards which you has just received here',
        HELP_WALLET_2: 'Use discount voucher at outlets in venue',
        HELP_LEADERBOARD_LABEL: 'Leaderboard',
        HELP_LEADERBOARD_1: 'Ranking participants based on the score which they have achieved in the 3rd challenge each quest',
        HELP_LEADERBOARD_2: 'Top 50 winners every week will get reward from event organizer',
        HELP_LEADERBOARD_3: 'Once new quest starts, the leaderboard will be refreshed',
    },
}
let lang = "EN";
export const GetText = id => texts[lang][id];
export const GetLang = ()=>{return lang};
